ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName = "Perma Weapons NPC"
ENT.Author = "liliaplayer"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.RenderGroup = RENDERGROUP_BOTH
ENT.Category = "Lilia"
ENT.NoPhysgun = true
ENT.NoRemover = true
ENT.IsPersistent = true
