MODULE.name = "Realistic Damage"
MODULE.author = "Samael"
MODULE.discord = "@liliaplayer"
MODULE.desc = "Adds configurable hit-location damage modifiers for a more grounded combat experience."
MODULE.version = "1.0.0"