local extracted_strings = {
    "  No snapshots found\\n",
    " (...)",
    " (received: ",
    " - Available\\n",
    " - Missing\\n",
    " .. L(\"accessToolPrivilege\", formattedTool) .. ",
    " .. args[1] .. ",
    " .. classID .. ",
    " .. classUID .. ",
    " .. estr .. ",
    " .. faction.uniqueID .. ",
    " .. flagName .. ",
    " .. itemType .. ",
    " .. key .. ",
    " .. lia.db.escape(field) .. ",
    " .. lia.db.escape(gamemode) .. ",
    " .. lia.db.escape(json) .. ",
    " .. lia.db.escape(k) .. ",
    " .. lia.db.escape(key) .. ",
    " .. lia.db.escape(nk) .. ",
    " .. lia.db.escape(tostring(column.default)) .. ",
    " .. lia.db.escape(tostring(defaultValue)) .. ",
    " .. lia.db.escape(util.TableToJSON(value)) .. ",
    " .. lia.db.escape(value) .. ",
    " .. name .. ",
    " .. tbl:gsub(",
    " .. tostring(a) .. ",
    " .. tostring(b) .. ",
    " .. tostring(d) .. ",
    " .. tostring(k) .. ",
    " .. tostring(key) .. ",
    " .. tostring(v.default) .. ",
    " .. usergroup .. ",
    " ADD COLUMN ",
    " AND id = ",
    " AND itemID = ",
    " AND key = '",
    " AND map = ",
    " DEFAULT '",
    " D_HT 999",
    " D_LI 999",
    " LIMIT 1",
    " NOT NULL",
    " ORDER BY ",
    " ORDER BY id DESC LIMIT ",
    " PRIMARY KEY",
    " RENAME TO ",
    " Started re-downloading stored sounds...\\n",
    " does not exist",
    " not found",
    " when applying preset ",
    " | Position: ",
    "!%Y-%m-%dT%H:%M:%SZ",
    "!blind ",
    "!bring ",
    "!freeze ",
    "!gag ",
    "!goto ",
    "!ignite ",
    "!jail ",
    "!mute ",
    "!respawn ",
    "!return ",
    "!slay ",
    "!unblind ",
    "!unfreeze ",
    "!ungag ",
    "!unmute ",
    "#Console",
    "#spawnmenu.category.addons",
    "#spawnmenu.category.addonslegacy",
    "#spawnmenu.category.downloads",
    "#spawnmenu.category.entities",
    "#spawnmenu.category.games",
    "#spawnmenu.category.npcs",
    "#spawnmenu.category.postprocess",
    "#spawnmenu.category.vehicles",
    "#spawnmenu.category.weapons",
    "#spawnmenu.menu.copy",
    "#spawnmenu.menu.delete",
    "#weapon_alyxgun",
    "#weapon_annabelle",
    "#weapon_citizenpackage",
    "#weapon_citizensuitcase",
    "#weapon_oldmanharpoon",
    "$alpha",
    "$basetexture",
    "$blur",
    "$c0_x",
    "$color",
    "$color2",
    "$pixshader",
    "$texture1",
    "$translucent",
    "$vertexalpha",
    "$vertexshader",
    "$viewprojmat",
    "%%[^%%]",
    "%.%.",
    "%.%w+$",
    "%.([%w]+)$",
    "%.([^%.]+)$",
    "%.0f, %.0f, %.0f",
    "%.2f %s",
    "%.2f%%",
    "%.mdl$",
    "%.png$",
    "%.txt$",
    "%.wav$",
    "%02i:%02i:%02i",
    "%S+",
    "%Y-%m-%d %H:%M:%S",
    "%[([-%d%.]+)%s+([-%d%.]+)%s+([-%d%.]+)%]",
    "%[([-%d%.]+),%s*([-%d%.]+),%s*([-%d%.]+)%]",
    "%\\\"",
    "%b**",
    "%d%s",
    "%d+",
    "%d+%.%d+%.%d+%.%d+(:%d*)?",
    "%d. %s\\n   %s %s | %s\\n\\n",
    "%s %s",
    "%s %s %s %s %d %d",
    "%s (%s)",
    "%s (%s, %s)",
    "%s DATETIME",
    "%s FLOAT",
    "%s INT",
    "%s TEXT",
    "%s TINYINT(1)",
    "%s VARCHAR(%d)",
    "%s | %s | %s",
    "%s+",
    "%s+$",
    "%s, %02d %s %04d, %02d:%02d:%02d",
    "%s, %s %02d, %04d, %02d:%02d:%02d%s",
    "%s[%s]",
    "%s[%s]: >> [%s](%s,%s)",
    "%s_%.0f_%.0f_%.0f",
    "%{([-%d%.]+)%s+([-%d%.]+)%s+([-%d%.]+)%}",
    "%{([-%d%.]+),%s*([-%d%.]+),%s*([-%d%.]+)%}",
    "&amp;",
    "&gt;",
    "&lt;",
    "' AND lia_characters.faction = ",
    "' AND steamID = ",
    "' WHERE key = 'h' AND invID IN (SELECT invID FROM lia_inventories WHERE charID IS NOT NULL)",
    "' WHERE key = 'w' AND invID IN (SELECT invID FROM lia_inventories WHERE charID IS NOT NULL)",
    "' failed or returned invalid result",
    "' is missing from stored configs",
    "' not found in stored configs",
    "' to vendor.",
    "'. Must use table with 'onPress' function. (Function: lia.keybind.add)",
    "'\\n",
    "(%a)([%w]*)",
    "(%d+),?",
    "(%s?[%S]+)",
    "(%x)",
    "(.+)/[^/]+$",
    "([^/\\\\]+)%.lua$",
    "([^/]+)$",
    "([_%w]+)",
    ") Angle:(",
    ") VALUES ",
    ") VALUES (",
    "):\\n",
    ")\\n",
    "*.*",
    "+jump",
    "+speed",
    "+use",
    ", SteamID: ",
    ", classes = ",
    ", reason=",
    ", type: ",
    ", value=",
    "----------------------------------------\\n",
    "-speed",
    "...",
    ".ImpactSoft",
    ".dat",
    ".gma",
    ".mdl",
    ".mp3",
    ".ogg",
    ".stepleft",
    ".stepright",
    ".vmt",
    ".wav",
    "0 0 0",
    "0 B",
    "127.0.0.1",
    "16x16",
    "2.0.1",
    "<color=",
    "<dx90",
    "<font=",
    "<img=",
    "@descChanged",
    "@enterAmount",
    "@giveMoney",
    "@liliaplayer",
    "@noPerm",
    "A Staff Character, Discord: ",
    "Active tab: Overview",
    "An inventory has a missing item",
    "Angle%(([-%d%.]+),%s*([-%d%.]+),%s*([-%d%.]+)%)",
    "Angle: ",
    "Available fonts (",
    "BEGIN TRANSACTION",
    "Book Antiqua",
    "Bunny Hop",
    "Choose a lilia theme...",
    "Combined: %d downloaded | %d stored",
    "Content-Type",
    "DATA/",
    "DESCRIBE lia_doors",
    "Dark Mono",
    "Data must be a table",
    "Download progress: %d active, %d queued, %d/%d images, %d/%d sounds",
    "DropDelay.",
    "EquipDelay.",
    "Faction Group",
    "Failed to SetAngles for entity '%s' at %s. Angle: %s (%s) - %s",
    "Failed to insert batch ",
    "Failed to parse JSON data: ",
    "Failed to query table ",
    "Failed to read snapshot file",
    "File validation failed: ",
    "Half-Life 2",
    "Images: %d downloaded | %d stored",
    "Images: %d/%d completed (%d failed)",
    "Invalid angle for entity '%s' at %s: %s (%s)",
    "Invalid snapshot format",
    "Inventory data is required",
    "Inventory type is required",
    "Lilia Skin",
    "Lilia frame notification!",
    "Map Entities",
    "Missing fonts (",
    "Model must be a string",
    "Montserrat Bold",
    "Montserrat Medium",
    "Montserrat Regular",
    "N/A",
    "Note: Fonts are checked against system font list or by testing font creation.\\n",
    "PRAGMA table_info(",
    "PRAGMA table_info(lia_characters)",
    "PRAGMA table_info(lia_doors)",
    "PRIMARY KEY (",
    "Palatino LT STD",
    "Palatino Linotype",
    "Player Entities",
    "Promise{state=",
    "SAM | Admin Mod",
    "SAM.Chat.Asay",
    "STEAM_0:1:464054146",
    "Simfphys Vehicles",
    "Sit Anywhere",
    "Snapshot file ",
    "Sounds: %d downloaded | %d stored",
    "Sounds: %d/%d completed (%d failed)",
    "Staff - ",
    "Storage name is required",
    "TakeDelay.",
    "Target table ",
    "Trunk name is required",
    "UNIQUE constraint failed: lia_config",
    "UnequipDelay.",
    "Vector%(([-%d%.]+),%s*([-%d%.]+),%s*([-%d%.]+)%)",
    "Vector: ",
    "Vector: (",
    "Vehicle class must be a string",
    "Warning: system.GetFonts() not available, using fallback font testing method.\\n",
    "X%x;",
    "[%s %s%s]",
    "[,]",
    "[-%d%.]+",
    "[<>\\\"\\\\|]",
    "[Asset Download] ",
    "[HotReload] ",
    "[LOG] ",
    "[Lilia] ",
    "[Lilia] Font checking is only available on the client.\\n",
    "[Sound Download] ",
    "[WARNING ISSUED] Admin: %s (%s) | Target: %s (%s) | Reason: %s | Total Warnings: %d",
    "[WARNING REMOVED] Admin: %s (%s) | Target: %s (%s) | Original Admin: %s (%s) | Reason: %s | Index: %d",
    "[WebImage] Cleanup complete: %d files removed",
    "[WebImage] Removed corrupted file: %s",
    "[WebImage] Removed from cache: %s",
    "[WebImage] Removed unreadable file: %s",
    "[WebSound]",
    "[WebSound]  - %s",
    "[WebSound] %s (%d bytes)",
    "[WebSound] ? Could not read: %s",
    "[WebSound] ? Invalid: %s - %s",
    "[WebSound] Cleanup complete: %d files removed",
    "[WebSound] Removed corrupted file: %s (%s)",
    "[WebSound] Removed from cache: %s",
    "[WebSound] Removed unreadable file: %s",
    "[WebSound] Validation complete: %d valid, %d invalid",
    "[{}%[%]]",
    "\\226\\128\\139#",
    "\\255\\250",
    "\\255\\251",
    "\\\\;",
    "\\n[Lilia] Checking font availability...\\n",
    "\\n\\n",
    "^%d+$",
    "^%d+%.%d+%.%d+%.%d+$",
    "^%l",
    "^%s*(.-)%s*$",
    "^%s*([-%d%.]+)%s+([-%d%.]+)%s+([-%d%.]+)%s*$",
    "^%s+",
    "^(%S+)%s+(.*)$",
    "^(.-)%sago$",
    "^(.-)(%d+)b$",
    "^([^%(]+)",
    "^([^%.]+)%.(%d+)$",
    "^/([^ ]+)",
    "^127%.0%.0%.1",
    "^ID3",
    "^OggS",
    "^RIFF",
    "^STEAM_%d+:%d+:%d+$",
    "^STEAM_%d:%d:%d+$",
    "^[%d%.%-%s]+$",
    "^[^/]+/",
    "^addons/",
    "^arc9_ammo_",
    "^arccw_ammo_",
    "^data/websounds/",
    "^download/",
    "^http",
    "^https://",
    "^https?://",
    "^https?://([^/]+)",
    "^https?://[^/]+/(.+)$",
    "^lia_",
    "^lilia/",
    "^lilia/webimages/",
    "^lilia/websounds/",
    "^localhost",
    "^metal$",
    "^models/",
    "^property_",
    "^tool_",
    "^webimages/",
    "^websounds/",
    "_release$",
    "`lia_",
    "addons/",
    "addons/*",
    "adminSteamID = ",
    "ai_expression_optimization 1",
    "application/json",
    "bot\\n",
    "buttons/button14.wav",
    "buttons/button15.wav",
    "buttons/button16.wav",
    "buttons/button17.wav",
    "buttons/lightswitch2.wav",
    "category = ",
    "charID = ",
    "cl_cmdrate 66",
    "cl_interp_ratio 2",
    "cl_lagcompensation 1",
    "cl_localnetworkbackdoor 1",
    "cl_smoothtime 0.05",
    "cl_threaded_bone_setup 1",
    "cl_timeout 3600",
    "cl_updaterate 66",
    "class C_AI_BaseNPC",
    "common/talk.wav",
    "common/wpn_denyselect.wav",
    "createShaderMat: tex must be a string",
    "data/",
    "data/rndx_shaders_",
    "doors/default_locked.wav",
    "doors/door_latch1.wav",
    "doors/door_latch3.wav",
    "download/materials",
    "download/models",
    "download/sound",
    "downloads not allowed",
    "duplicate column name:",
    "empty file",
    "entities/",
    "entity:",
    "fast_fogvolume 1",
    "file too large",
    "file too small",
    "filesystem_max_stdio_read 64",
    "filesystem_unbuffered_io 0",
    "friends/friend_join.wav",
    "gamemode = ",
    "gamemode IS NULL",
    "gamemodes/Lilia/data/",
    "games/16/",
    "garrysmod/balloon_pop_cute.wav",
    "garrysmod/content_downloaded.wav",
    "garrysmod/ui_click.wav",
    "gmod_mcore_test 1",
    "gmod_physiterations 4",
    "id = ",
    "in_usekeyboardsampletime 1",
    "invID = ",
    "invalid mp3 format",
    "invalid url: ",
    "itemID = ",
    "items/ammo_pickup.wav",
    "items/ammocrate_open.wav",
    "items/medshot4.wav",
    "items/suitchargeok1.wav",
    "lia(%w+)Button",
    "lia.doors.AddPreset: Missing required parameters (mapName, presetData)",
    "liaVerifyCheats:",
    "lia_%",
    "lia_characters.name, lia_characters.faction, lia_characters.id, lia_characters.steamID, lia_characters.lastJoinTime, lia_players.lastOnline, lia_characters.class, lia_characters.playtime",
    "lia_characters.schema = '",
    "lilia/",
    "lilia/gamemode",
    "lilia/gamemode/core/derma",
    "lilia/gamemode/core/libraries/thirdparty",
    "lilia/gamemode/entities",
    "lilia/gamemode/items",
    "lilia/gamemode/languages",
    "lilia/gamemode/modules",
    "lilia/snapshots",
    "lilia/snapshots/",
    "lilia/snapshots/*",
    "lilia/webimages/",
    "lilia/websounds/",
    "lilia/workshop",
    "map = ",
    "map IS NULL",
    "mat_framebuffercopyoverlaysize 0",
    "mat_managedtextures 0",
    "mat_powersavingsmode 0",
    "mat_queue_mode 2",
    "materials/",
    "me's",
    "mem_max_heapsize_dedicated 131072",
    "mem_min_heapsize 131072",
    "min and max",
    "misc.Bunny Hop",
    "models/",
    "models/.*",
    "models/Gibs/HGIBS.mdl",
    "models/Humans/Group02/male_07.mdl",
    "models/error.mdl",
    "models/models/",
    "models/mossman.mdl",
    "models/player/group01/female_01.mdl",
    "models/player/group01/female_02.mdl",
    "models/player/group01/female_03.mdl",
    "models/player/group01/female_04.mdl",
    "models/player/group01/female_05.mdl",
    "models/player/group01/female_06.mdl",
    "models/player/group01/male_01.mdl",
    "models/player/group01/male_02.mdl",
    "models/player/group01/male_03.mdl",
    "models/player/group01/male_04.mdl",
    "models/player/group01/male_05.mdl",
    "models/player/group01/male_06.mdl",
    "models/player/phoenix.mdl",
    "models/player/police.mdl",
    "models/props/cs_office/money.mdl",
    "models/props_c17/BriefCase001a.mdl",
    "models/props_c17/SuitCase001a.mdl",
    "models/props_c17/suitcase001a.mdl",
    "models/props_c17/suitcase_passenger_physics.mdl",
    "models/props_interiors/pot01a.mdl",
    "models/props_junk/cardboard_box001a.mdl",
    "models/props_junk/cardboard_box002b.mdl",
    "models/props_junk/wood_crate001a.mdl",
    "models/props_lab/bindergraylabel01b.mdl",
    "models/weapons/c_arms.mdl",
    "models/weapons/c_arms_animations.mdl",
    "models/weapons/v_stunstick.mdl",
    "models/weapons/w_bugbait.mdl",
    "models/weapons/w_eq_fraggrenade.mdl",
    "models/weapons/w_package.mdl",
    "models/weapons/w_pistol.mdl",
    "models/weapons/w_stunbaton.mdl",
    "mono 3d",
    "mp_show_voice_icons 0",
    "name = ",
    "name LIKE \\\"%",
    "net_maxfilesize 64",
    "no file extension",
    "no url",
    "noclamp smooth",
    "not provided",
    "npc/vort/claw_swing",
    "npc/vort/claw_swing1.wav",
    "npc/vort/claw_swing2.wav",
    "npc:",
    "out of character",
    "outlands-rp/ui/ui_return.wav",
    "pac_enable 0",
    "pac_enable 1",
    "physics/body/body_medium_impact_hard",
    "physics/cardboard/cardboard_box_break",
    "physics/cardboard/cardboard_box_impact_soft2.wav",
    "physics/plastic/plastic_box_impact_hard1.wav",
    "physics/plastic/plastic_box_impact_hard2.wav",
    "physics/plastic/plastic_box_impact_hard3.wav",
    "physics/plastic/plastic_box_impact_hard4.wav",
    "physics/wood/wood_crate_impact_hard",
    "physics/wood/wood_crate_impact_hard2.wav",
    "physics/wood/wood_crate_impact_hard3.wav",
    "player/breathe1.wav",
    "player:",
    "playerSteamID = ",
    "pp/blurscreen",
    "properties_friently/hostile",
    "properties_friently/hostile_remove",
    "r_queued_ropes 1",
    "r_radiosity 4",
    "r_threaded_particles 1",
    "rate 1048576",
    "requesterSteamID = ",
    "resource/fonts/montserrat-bold.ttf",
    "resource/fonts/montserrat-medium.ttf",
    "resource/fonts/montserrat-regular.ttf",
    "s\", \"/action",
    "say \"/charban ",
    "say \"/charbanoffline ",
    "say \"/charunban ",
    "say \"/charunbanoffline ",
    "say \"/charwipe ",
    "say \"/charwipeoffline ",
    "say /",
    "say /charlist ",
    "say /classunwhitelist ",
    "say /classwhitelist ",
    "say /dooraddfaction '",
    "say /doorremoveclass '",
    "say /doorremoveclass ''",
    "say /doorremovefaction '",
    "say /doorsetclass '",
    "say /giveflag ",
    "say /pflaggive ",
    "say /pflagtake ",
    "say /plytransfer ",
    "say /plyunwhitelist ",
    "say /plyviewclaims ",
    "say /plywhitelist ",
    "say /setclass ",
    "say /takeflag ",
    "say /viewtickets ",
    "say /viewwarns ",
    "say /viewwarnsissued ",
    "sbox_noclip 0",
    "schema = ",
    "schema = '",
    "serverguard.CAMI.OnPrivilegeRegistered",
    "serverguard.CAMI.PlayerHasAccess",
    "settings/spawnlist/",
    "smooth mips noclamp",
    "sound/",
    "spawnicons/",
    "steamID = ",
    "studio_queue_mode 1",
    "sv_allowcslua 0",
    "sv_allowdownload 0",
    "sv_allowupload 0",
    "sv_kickerrornum 0",
    "sv_maxcmdrate 66",
    "sv_maxrate 30000",
    "sv_maxupdaterate 66",
    "sv_mincmdrate 30",
    "sv_minrate 5000",
    "sv_pac_webcontent_limit 35840\\n",
    "threadpool_affinity 64",
    "ticketsystem-",
    "timestamp >= ",
    "ui/hint.wav",
    "urlimages/",
    "urlsounds/",
    "vehicle:",
    "vgui/gradient-d",
    "vgui/gradient-l",
    "vgui/gradient-r",
    "vgui/gradient-u",
    "vgui/gradient_down",
    "vgui/gradient_up",
    "vgui/white",
    "warnerSteamID = ",
    "x%x;",
    "x86-64",
    "{(%w-)}",
    "Категория"
}

return extracted_strings