#!/usr/bin/env python3
"""
Function Comparison Report Tool

This script helps manage function documentation analysis by maintaining
lists of functions that should not be checked during documentation validation.
"""

# Functions that should NOT be checked during documentation analysis
# These are typically internal functions, callbacks, or auto-generated code
FUNCTIONS_NOT_TO_CHECK = {
    # Derma/UI related functions that are internal callbacks
    "lia.derma.menuPlayerSelector.btn_close.DoClick",

    # Add other functions here as needed
    # Examples:
    # "internal.helperFunction",
    # "autoGenerated.callback",
}

# Functions that should be checked (explicit allowlist)
# If a function is not in this list and not in FUNCTIONS_NOT_TO_CHECK,
# it will be flagged for documentation review
FUNCTIONS_TO_CHECK = {
    # Core framework functions that need documentation
    "lia.util.*",
    "lia.config.*",
    "lia.database.*",

    # Add other patterns here as needed
}

def should_check_function(function_name):
    """
    Determine if a function should be checked for documentation.

    Args:
        function_name (str): The name of the function to check

    Returns:
        bool: True if the function should be checked, False otherwise
    """
    # First check if it's explicitly in the "not to check" list
    if function_name in FUNCTIONS_NOT_TO_CHECK:
        return False

    # Then check if it matches any pattern in the "to check" list
    for pattern in FUNCTIONS_TO_CHECK:
        if function_name.startswith(pattern.replace("*", "")):
            return True

    # Default behavior: check the function
    return True

def get_exclusion_reason(function_name):
    """
    Get the reason why a function is excluded from checking.

    Args:
        function_name (str): The name of the function

    Returns:
        str: Reason for exclusion, or None if not excluded
    """
    if function_name in FUNCTIONS_NOT_TO_CHECK:
        return "Explicitly excluded from documentation checking"
    return None

if __name__ == "__main__":
    # Example usage
    test_functions = [
        "lia.derma.menuPlayerSelector.btn_close.DoClick",
        "lia.util.getTableSize",
        "some.unknown.function"
    ]

    for func in test_functions:
        should_check = should_check_function(func)
        reason = get_exclusion_reason(func)
        print(f"{func}: Check={should_check}, Reason={reason}")
