local fonts = {"resource/fonts/specialelite.ttf", "resource/fonts/montserrat-bold.ttf", "resource/fonts/montserrat-medium.ttf", "resource/fonts/montserrat-regular.ttf"}
local networkStrings = {"liaWeaponOverrideUpdate", "liaSitSitFacing", "liaWeaponOverrideSync", "liaActBar", "liaAdminModeSwapCharacter", "liaAnimationStatus", "liaArgumentsRequest", "liaArgumentsRequestCancel", "liaAssureClientSideAssets", "liaAttributeData", "liaBigTableAck", "liaBinaryQuestionRequest", "liaBinaryQuestionRequestCancel", "liaPopupQuestionRequest", "liaBlindFade", "liaBlindTarget", "liaButtonRequest", "liaCfgList", "liaCfgSet", "liaCharChoose", "liaCharCreate", "liaCharDelete", "liaCharDeleted", "liaCharInfo", "liaCharKick", "liaCharList", "liaCharRequest", "liaCharSet", "liaCharVar", "liaCharacterData", "liaCharacterInvList", "liaClassUpdate", "liaCmdArgPrompt", "liaCommandData", "liaDataSync", "liaDialogSync", "liaDoorDataBulk", "liaEmitUrlSound", "liaGlobalVar", "liaGroupPermChanged", "liaGroupsAdd", "liaGroupsRemove", "liaGroupsRename", "liaGroupsRequest", "liaGroupsSetPerm", "liaInvAct", "liaInvData", "liaInvQuantity", "liaInventoryAdd", "liaInventoryData", "liaInventoryDelete", "liaInventoryInit", "liaInventoryRemove", "liaItemDelete", "liaItemInstance", "liaItemRotate", "liaKeybindServer", "liaManagesitrooms", "liaModifyCharacterFlags", "liaModifyFlags", "liaNetDel", "liaNetLocal", "liaNetStreamData", "liaNetVar", "liaNpcCustomize", "liaNpcDialogServerCallback", "liaNpcDialogRequestResponse", "liaNpcDialogDeliverResponse", "liaNpcDialogNodeSelect", "liaNpcDialogNodeResult", "liaNotificationData", "liaNotifyLocal", "liaOpenInvMenu", "liaOpenNpcDialog", "liaOptionsRequest", "liaOptionsRequestCancel", "liaPacPartAdd", "liaPacPartRemove", "liaPacPartReset", "liaPacSync", "liaPlayerInteractCategories", "liaPlayerInteractSync", "liaPlayerRespawn", "liaProvideInteractOptions", "liaRegenChat", "liaRemoveFOne", "liaRequestDropdown", "liaRequestDropdownCancel", "liaRequestInteractOptions", "liaRequestNPCSelection", "liaRequestOnlineStaffData", "liaRunInteraction", "liaSendTableUI", "liaSetMainCharacter", "liaSetWaypoint", "liaStaffDiscordPrompt", "liaStorageOpen", "liaStorageSync", "liaStorageSyncRequest", "liaStringRequest", "liaStringRequestCancel", "liaWeaponRuntimeOverrideUpdate", "liaWeaponRuntimeOverrideSync", "liaWeaponRuntimeOverrideReset", "liaSyncGesture", "liaTransferItem", "liaUpdateAdminGroups", "liaUpdateAdminPrivileges", "liaVendorEdit", "liaVendorSyncPresets", "liaVendorPropertySync", "liaWaypointReached", "liaWorkshopDownloaderInfo", "liaWorkshopDownloaderRequest", "liaWorkshopDownloaderStart", "liaRemoveFeaturePosition"}
DeriveGamemode("sandbox")
AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("core/libraries/loader.lua")
include("shared.lua")
for _, fontFile in ipairs(fonts) do
    resource.AddSingleFile(fontFile)
end

for _, netString in ipairs(networkStrings) do
    util.AddNetworkString(netString)
end

resource.AddWorkshop("3527535922")